spring:
  application:
    name: tickets
  datasource:
    url: jdbc:postgresql://localhost:5432/tickets
    jdbcUrl: jdbc:postgresql://localhost:5432/tickets
    username: postgres
    password: postgres

  flyway:
    enabled: false
    baseline-on-migrate: false
    locations:
      - db/migrations

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    org.springframework.batch: DEBUG